name: eggpve
version: '1.0-SNAPSHOT'
main: org.totemcraft.eggpve.Eggpve
api-version: '1.18'
authors: [ PutEgg ]
description: egg's tool for clay pve
website: totemcraft.org
commands:
  eggpve:
    description: command for Eggpve plugin.
    usage: /<command> [ pos1 | pos2 | add | list | del | reload | tp | show ] [id] [content]
    aliases: [ep]
